QDENGINE: Fix qdInventoryCellSet::put_object() build error on OpenBSD
This is meant to return a bool; the NULL used there triggers a build error
on (at least) OpenBSD/7.5 with default clang++:

error: cannot initialize return object of type 'bool' with an rvalue of type 'std::nullptr_t'
                return NULL;
                       ^~~~
/usr/include/sys/_null.h:12:14: note: expanded from macro 'NULL'
                ^~~~~~~

Introduced in commit d9c9f38f7e456f39b196e013310460ad7f72eedd.